apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: flux-system
spec:
  releaseName: argo-cd
  targetNamespace: argo-cd
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: 7.8.3
      sourceRef:
        kind: HelmRepository
        name: argo-cd-repo
        namespace: flux-system
  install:
    createNamespace: true
  valuesFrom:
    - kind: Secret
      name: argo-cd-protected-parameters
      valuesKey: argoUrl
      targetPath: server.ingress.hosts[0].host
    - kind: Secret
      name: argo-cd-protected-parameters
      valuesKey: argoUrl
      targetPath: configs.cm.url
    - kind: Secret
      name: argo-cd-protected-parameters
      valuesKey: issuer
      targetPath: configs.cm.oidc.issuer
    - kind: Secret
      name: argo-cd-protected-parameters
      valuesKey: clientId
      targetPath: configs.cm.oidc.clientID
    - kind: Secret
      name: argo-cd-protected-parameters
      valuesKey: clientSecret
      targetPath: configs.cm.oidc.clientSecret
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: webapprouting.kubernetes.azure.com
        annotations:
          kubernetes.io/ingress.class: "webapprouting.kubernetes.azure.com"
        tls: false
    configs:
      params:
        server.insecure: "true"
      cm:
        oidc.config: |
          name: Azure
          requestedScopes: ["openid", "profile", "email"]
          requestedIDTokenClaims:
            groups:
              essential: true
    dex:
      enabled: false
