apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: flux-system
spec:
  releaseName: argo-cd
  targetNamespace: argo-cd
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: 7.8.3
      sourceRef:
        kind: HelmRepository
        name: argo-cd-repo
        namespace: flux-system
  install:
    createNamespace: true
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: webapprouting.kubernetes.azure.com
        annotations:
          kubernetes.io/ingress.class: "webapprouting.kubernetes.azure.com"
        hosts:
          - host: "{{ .ValueFrom.secret.argo-cd-protected-parameters.argoUrl }}"
            paths:
              - path: /
                pathType: Prefix
    configs:
      params:
        server.insecure: "true"
      cm:
        url: "http://{{ .ValueFrom.secret.argo-cd-protected-parameters.argoUrl }}"
        oidc.config: |
          name: Azure
          issuer: "{{ .ValueFrom.secret.argo-cd-protected-parameters.issuer }}"
          clientID: "{{ .ValueFrom.secret.argo-cd-protected-parameters.clientId }}"
          clientSecret: "{{ .ValueFrom.secret.argo-cd-protected-parameters.clientSecret }}"
          requestedScopes: ["openid", "profile", "email"]
          requestedIDTokenClaims:
            groups:
              essential: true
    dex:
      enabled: false
