apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argo-cd-kustomization
  namespace: flux-system
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml