apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argo-cd-kustomization
  namespace: flux-system
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
secretGenerator:
  - name: argo-cd-oidc-secret
    namespace: argo-cd
    literals:
      - oidc.azure.clientSecret=$clientSecret
      - oidc.azure.clientId=$clientId
      - oidc.azure.issuer=$issuer
      - oidc.azure.argoUrl=$argoUrl